# Generated by Django 3.2.12 on 2024-05-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamprecord',
            name='region',
            field=models.IntegerField(default=1),
        ),
    ]
